#os: osx
language: python
python:
  - 3.5
  - 3.6
services:
  - mysql
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
script: sudo python app.py