version: '3'
services:
  web:
    image: sim:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    links:
     - db
    ports:
     - "5004:80"
    volumes:
     - .:/code
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: brovis
      MYSQL_DATABASE: BROVIS
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

# version: '3'
# services:
#   web:
#     build: .
#     ports:
#      - "5050:80"
#     volumes:
#      - .:/code
#   redis:
#     image: "redis:alpine"